### ISSUE TITLE
Reactions not in sync on MM with Teams

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#32] opened 2023-03-28 11:44 UTC
Reactions added on Teams are not visible on MM.

**Steps to reproduce:-**

1. Go to Teams linked channel.
2. Add any reaction on the desired message.
3. Go to the channel linked in MM.

The reaction added are not visible in MM channel.

![image](https://user-images.githubusercontent.com/116162036/228225596-4390bbdb-ba20-4145-bf11-63c882b1de0d.png)
![image (1)](https://user-images.githubusercontent.com/116162036/228225615-fc2fc65e-4798-466e-8bdb-58a1a24040a4.png)

**Comment by jespino** [comment] 2023-03-30 16:57
I'm not able to reproduce it locally

**Comment by manojmalik20** [comment] 2023-04-14 10:44
Fixed with PR #73

**Closed by manojmalik20** 2023-04-14 10:44 UTC
Labels: Type/Bug
