### ISSUE TITLE
Messages are still visible for users who are not in the linked MM channel but are in the Teams channel

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#65] opened 2023-04-05 10:14 UTC
If a user is NOT a member of the linked channel in MM, but IS a member of the linked channel in Teams, then the message sent by that particular user through Teams is visible in MM channel. Also, on hovering the profile pop-up is also visible for that particular user.

**Steps to reproduce:-**
1. Do any desired message through Teams by the user who is not a member of MM channel.
2. Verify it on MM channel.

![image](https://user-images.githubusercontent.com/116162036/230051157-c023397d-7e6d-47e2-9e0c-6d5769d876b3.png)

![image](https://user-images.githubusercontent.com/116162036/230051197-3beb4b61-7e1a-4dd8-ac99-1d63b19a5fe3.png)

![image](https://user-images.githubusercontent.com/116162036/230051309-09ba7334-eb5f-4333-add9-38ab1ee334b3.png)

![image](https://user-images.githubusercontent.com/116162036/230051376-665f00eb-ff29-464f-82e0-9e4ccb8d9748.png)

**Comment by mkdbns** [comment] 2023-04-28 13:05
@jespino , for this, this issue is really about resolving the users on each side of a linked channel. So with this, the memberships align and messages are posted by a user account that is actually in the channel.

**Comment by ayusht2810** [comment] 2023-05-22 09:59
Here is the doc for different cases while handling syncing channel members functionality
https://docs.google.com/document/d/1A36GfubwP1Do6-eiSN2HN-EPteBh5VzzkXDhOLXm4ws/edit?usp=sharing

**Comment by lieut-data** [comment] 2023-11-20 21:26
@jespino & @jasonblais, I'm inclined to close this issue (and related pull request). As I understand it, the problem is that it looks like a user who isn't in the channel is posting into the channel because they were a member in the "other" product. While this is surprising, it seems "correct" and a minor improvement to force the user into the channel to make it real.

Thoughts?

**Comment by jasonblais** [comment] 2023-11-20 21:58
@lieut-data Great question.

There has previously been a suggestion from the customer to make it more obvious when a message is synced from another platform. An idea they had was a visual indication/badge within the post when a message in Mattermost was synced over from MS Teams (and vice versa).

0/5 on the actual solution, but wanted to share additional context from the customer's perspective.

**Comment by lieut-data** [comment] 2023-11-21 14:18
Thanks, @jasonblais. Unlike in shared channels, the users can be active on "both sides", so it's necessary to flag things post-by-post vs. user-by-user. We can't do that today, as we have no infrastructure to tag posts in such a fashion.

I'm going to close this out for now as the specific issue raised here isn't a bug. Let's revisit your/their suggestion as a possible future step if this remains confusing.

**Closed by lieut-data** 2023-11-21 14:18 UTC
