### ISSUE TITLE
User sync is failing due to duplicates unexpectedly

### ISSUE THREAD

**Issue by mkdbns** [mattermost/mattermost-plugin-msteams-sync#145] opened 2023-05-25 11:44 UTC
We're seeing these errors in the logs at SN but duplicates are not expected in the clean instance here:

https://servicenow-test.test.mattermost.cloud/

{
  "caller": "app/plugin_api.go:976",
  "error": "createUserOrGuest: An account with that email already exists.",
  "level": "error",
  "msg": "Unable to sync user",
  "plugin_id": "com.mattermost.msteams-sync",
  "timestamp": "2023-05-25 00:49:55.648 Z"
}

**Comment by ayusht2810** [comment] 2023-05-29 06:10
The issue is resolved in the PR https://github.com/mattermost/mattermost-plugin-msteams-sync/pull/147. Closing the issue

**Closed by ayusht2810** 2023-05-29 06:10 UTC
Labels: Type/Bug
